//
//  RemoteControlServiceProtocol.swift
//  VideoPlayer
//
//  Created by Astrid Lin on 2025/12/18.
//

import Foundation

/// Protocol for remote control and Now Playing info management.
protocol RemoteControlServiceProtocol: AnyObject {

    /// Configures remote control command handlers.
    func setupCommands(handlers: RemoteCommandHandlers)

    /// Updates Now Playing info on lock screen.
    func updateNowPlayingInfo(_ info: NowPlayingInfo)

    /// Clears Now Playing info.
    func clearNowPlayingInfo()
}

// MARK: - Supporting Types

/// Remote control command callbacks.
struct RemoteCommandHandlers {
    var onPlay: (() -> Void)?
    var onPause: (() -> Void)?
    var onTogglePlayPause: (() -> Void)?
    var onNextTrack: (() -> Void)?
    var onPreviousTrack: (() -> Void)?
    var onSkipForward: ((TimeInterval) -> Void)?
    var onSkipBackward: ((TimeInterval) -> Void)?
    var onChangePlaybackPosition: ((TimeInterval) -> Void)?

    init(
        onPlay: (() -> Void)? = nil,
        onPause: (() -> Void)? = nil,
        onTogglePlayPause: (() -> Void)? = nil,
        onNextTrack: (() -> Void)? = nil,
        onPreviousTrack: (() -> Void)? = nil,
        onSkipForward: ((TimeInterval) -> Void)? = nil,
        onSkipBackward: ((TimeInterval) -> Void)? = nil,
        onChangePlaybackPosition: ((TimeInterval) -> Void)? = nil
    ) {
        self.onPlay = onPlay
        self.onPause = onPause
        self.onTogglePlayPause = onTogglePlayPause
        self.onNextTrack = onNextTrack
        self.onPreviousTrack = onPreviousTrack
        self.onSkipForward = onSkipForward
        self.onSkipBackward = onSkipBackward
        self.onChangePlaybackPosition = onChangePlaybackPosition
    }
}

/// Now Playing info for lock screen display.
struct NowPlayingInfo {
    var title: String?
    var artist: String?
    var duration: TimeInterval?
    var elapsedTime: TimeInterval?
    var playbackRate: Float
    var artwork: NowPlayingArtwork?
    var usePlaceholderArtwork: Bool  // Whether to use placeholder artwork generated by Service

    init(
        title: String? = nil,
        artist: String? = nil,
        duration: TimeInterval? = nil,
        elapsedTime: TimeInterval? = nil,
        playbackRate: Float = 0.0,
        artwork: NowPlayingArtwork? = nil,
        usePlaceholderArtwork: Bool = false
    ) {
        self.title = title
        self.artist = artist
        self.duration = duration
        self.elapsedTime = elapsedTime
        self.playbackRate = playbackRate
        self.artwork = artwork
        self.usePlaceholderArtwork = usePlaceholderArtwork
    }
}

/// Now Playing artwork image data.
struct NowPlayingArtwork {
    let imageData: Data
    let size: CGSize

    init(imageData: Data, size: CGSize) {
        self.imageData = imageData
        self.size = size
    }
}
